### PR TITLE
Search front pagination

### PR DESCRIPTION
**Pull request by callumfg**
Pagination working, submit anothe sighting working

### CODE REVIEW

**Review by chloejonessoftwire — COMMENTED** [review]
looks good!! :)

**Review by littlemauli — COMMENTED** [review]
looks good to me

**Review by ChristianMcc — COMMENTED** [review]
Looks great! I think we need to add a link in the nav bar for this page as currently you can't get to it easily :)

**Comment by chloejonessoftwire** [comment]
> Looks great! I think we need to add a link in the nav bar for this page as currently you can't get to it easily :)

Yvonne and I have done this on our PR :)

**Review by ChristianMcc — APPROVED** [review]
LGTM :)

**Pull request merged**
